// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payload.proto

package cc.ddrpa.security.totp.migrate.google.proto;

/**
 * Protobuf type {@code cc.ddrpa.security.totp.migrate.google.proto.Payload}
 */
public final class Payload extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cc.ddrpa.security.totp.migrate.google.proto.Payload)
    PayloadOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Payload.newBuilder() to construct.
  private Payload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Payload() {
    otpParameters_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Payload();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cc.ddrpa.security.totp.migrate.google.proto.OTPAuthMigrationPayload.internal_static_cc_ddrpa_security_totp_migrate_google_proto_Payload_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cc.ddrpa.security.totp.migrate.google.proto.OTPAuthMigrationPayload.internal_static_cc_ddrpa_security_totp_migrate_google_proto_Payload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cc.ddrpa.security.totp.migrate.google.proto.Payload.class, cc.ddrpa.security.totp.migrate.google.proto.Payload.Builder.class);
  }

  /**
   * Protobuf enum {@code cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm}
   */
  public enum Algorithm
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ALGORITHM_UNSPECIFIED = 0;</code>
     */
    ALGORITHM_UNSPECIFIED(0),
    /**
     * <code>ALGORITHM_SHA1 = 1;</code>
     */
    ALGORITHM_SHA1(1),
    /**
     * <code>ALGORITHM_SHA256 = 2;</code>
     */
    ALGORITHM_SHA256(2),
    /**
     * <code>ALGORITHM_SHA512 = 3;</code>
     */
    ALGORITHM_SHA512(3),
    /**
     * <code>ALGORITHM_MD5 = 4;</code>
     */
    ALGORITHM_MD5(4),
    ;

    /**
     * <code>ALGORITHM_UNSPECIFIED = 0;</code>
     */
    public static final int ALGORITHM_UNSPECIFIED_VALUE = 0;
    /**
     * <code>ALGORITHM_SHA1 = 1;</code>
     */
    public static final int ALGORITHM_SHA1_VALUE = 1;
    /**
     * <code>ALGORITHM_SHA256 = 2;</code>
     */
    public static final int ALGORITHM_SHA256_VALUE = 2;
    /**
     * <code>ALGORITHM_SHA512 = 3;</code>
     */
    public static final int ALGORITHM_SHA512_VALUE = 3;
    /**
     * <code>ALGORITHM_MD5 = 4;</code>
     */
    public static final int ALGORITHM_MD5_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Algorithm valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Algorithm forNumber(int value) {
      switch (value) {
        case 0: return ALGORITHM_UNSPECIFIED;
        case 1: return ALGORITHM_SHA1;
        case 2: return ALGORITHM_SHA256;
        case 3: return ALGORITHM_SHA512;
        case 4: return ALGORITHM_MD5;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Algorithm>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Algorithm> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Algorithm>() {
            public Algorithm findValueByNumber(int number) {
              return Algorithm.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cc.ddrpa.security.totp.migrate.google.proto.Payload.getDescriptor().getEnumTypes().get(0);
    }

    private static final Algorithm[] VALUES = values();

    public static Algorithm valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Algorithm(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm)
  }

  /**
   * Protobuf enum {@code cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount}
   */
  public enum DigitCount
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DIGIT_COUNT_UNSPECIFIED = 0;</code>
     */
    DIGIT_COUNT_UNSPECIFIED(0),
    /**
     * <code>DIGIT_COUNT_SIX = 1;</code>
     */
    DIGIT_COUNT_SIX(1),
    /**
     * <code>DIGIT_COUNT_EIGHT = 2;</code>
     */
    DIGIT_COUNT_EIGHT(2),
    ;

    /**
     * <code>DIGIT_COUNT_UNSPECIFIED = 0;</code>
     */
    public static final int DIGIT_COUNT_UNSPECIFIED_VALUE = 0;
    /**
     * <code>DIGIT_COUNT_SIX = 1;</code>
     */
    public static final int DIGIT_COUNT_SIX_VALUE = 1;
    /**
     * <code>DIGIT_COUNT_EIGHT = 2;</code>
     */
    public static final int DIGIT_COUNT_EIGHT_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DigitCount valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DigitCount forNumber(int value) {
      switch (value) {
        case 0: return DIGIT_COUNT_UNSPECIFIED;
        case 1: return DIGIT_COUNT_SIX;
        case 2: return DIGIT_COUNT_EIGHT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DigitCount>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DigitCount> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DigitCount>() {
            public DigitCount findValueByNumber(int number) {
              return DigitCount.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cc.ddrpa.security.totp.migrate.google.proto.Payload.getDescriptor().getEnumTypes().get(1);
    }

    private static final DigitCount[] VALUES = values();

    public static DigitCount valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DigitCount(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount)
  }

  /**
   * Protobuf enum {@code cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType}
   */
  public enum OtpType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OTP_TYPE_UNSPECIFIED = 0;</code>
     */
    OTP_TYPE_UNSPECIFIED(0),
    /**
     * <code>OTP_TYPE_HOTP = 1;</code>
     */
    OTP_TYPE_HOTP(1),
    /**
     * <code>OTP_TYPE_TOTP = 2;</code>
     */
    OTP_TYPE_TOTP(2),
    ;

    /**
     * <code>OTP_TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int OTP_TYPE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>OTP_TYPE_HOTP = 1;</code>
     */
    public static final int OTP_TYPE_HOTP_VALUE = 1;
    /**
     * <code>OTP_TYPE_TOTP = 2;</code>
     */
    public static final int OTP_TYPE_TOTP_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OtpType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OtpType forNumber(int value) {
      switch (value) {
        case 0: return OTP_TYPE_UNSPECIFIED;
        case 1: return OTP_TYPE_HOTP;
        case 2: return OTP_TYPE_TOTP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OtpType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OtpType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OtpType>() {
            public OtpType findValueByNumber(int number) {
              return OtpType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cc.ddrpa.security.totp.migrate.google.proto.Payload.getDescriptor().getEnumTypes().get(2);
    }

    private static final OtpType[] VALUES = values();

    public static OtpType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OtpType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType)
  }

  public interface OtpParametersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes secret = 1;</code>
     * @return Whether the secret field is set.
     */
    boolean hasSecret();
    /**
     * <code>optional bytes secret = 1;</code>
     * @return The secret.
     */
    com.google.protobuf.ByteString getSecret();

    /**
     * <code>optional string name = 2;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string issuer = 3;</code>
     * @return Whether the issuer field is set.
     */
    boolean hasIssuer();
    /**
     * <code>optional string issuer = 3;</code>
     * @return The issuer.
     */
    java.lang.String getIssuer();
    /**
     * <code>optional string issuer = 3;</code>
     * @return The bytes for issuer.
     */
    com.google.protobuf.ByteString
        getIssuerBytes();

    /**
     * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm algorithm = 4;</code>
     * @return Whether the algorithm field is set.
     */
    boolean hasAlgorithm();
    /**
     * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm algorithm = 4;</code>
     * @return The algorithm.
     */
    cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm getAlgorithm();

    /**
     * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount digits = 5;</code>
     * @return Whether the digits field is set.
     */
    boolean hasDigits();
    /**
     * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount digits = 5;</code>
     * @return The digits.
     */
    cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount getDigits();

    /**
     * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType type = 6;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType type = 6;</code>
     * @return The type.
     */
    cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType getType();

    /**
     * <code>optional int64 counter = 7;</code>
     * @return Whether the counter field is set.
     */
    boolean hasCounter();
    /**
     * <code>optional int64 counter = 7;</code>
     * @return The counter.
     */
    long getCounter();
  }
  /**
   * Protobuf type {@code cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters}
   */
  public static final class OtpParameters extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters)
      OtpParametersOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OtpParameters.newBuilder() to construct.
    private OtpParameters(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OtpParameters() {
      secret_ = com.google.protobuf.ByteString.EMPTY;
      name_ = "";
      issuer_ = "";
      algorithm_ = 0;
      digits_ = 0;
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OtpParameters();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cc.ddrpa.security.totp.migrate.google.proto.OTPAuthMigrationPayload.internal_static_cc_ddrpa_security_totp_migrate_google_proto_Payload_OtpParameters_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cc.ddrpa.security.totp.migrate.google.proto.OTPAuthMigrationPayload.internal_static_cc_ddrpa_security_totp_migrate_google_proto_Payload_OtpParameters_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters.class, cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters.Builder.class);
    }

    private int bitField0_;
    public static final int SECRET_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString secret_;
    /**
     * <code>optional bytes secret = 1;</code>
     * @return Whether the secret field is set.
     */
    @java.lang.Override
    public boolean hasSecret() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes secret = 1;</code>
     * @return The secret.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSecret() {
      return secret_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISSUER_FIELD_NUMBER = 3;
    private volatile java.lang.Object issuer_;
    /**
     * <code>optional string issuer = 3;</code>
     * @return Whether the issuer field is set.
     */
    @java.lang.Override
    public boolean hasIssuer() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string issuer = 3;</code>
     * @return The issuer.
     */
    @java.lang.Override
    public java.lang.String getIssuer() {
      java.lang.Object ref = issuer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          issuer_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string issuer = 3;</code>
     * @return The bytes for issuer.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIssuerBytes() {
      java.lang.Object ref = issuer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        issuer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALGORITHM_FIELD_NUMBER = 4;
    private int algorithm_;
    /**
     * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm algorithm = 4;</code>
     * @return Whether the algorithm field is set.
     */
    @java.lang.Override public boolean hasAlgorithm() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm algorithm = 4;</code>
     * @return The algorithm.
     */
    @java.lang.Override public cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm getAlgorithm() {
      @SuppressWarnings("deprecation")
      cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm result = cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm.valueOf(algorithm_);
      return result == null ? cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm.ALGORITHM_UNSPECIFIED : result;
    }

    public static final int DIGITS_FIELD_NUMBER = 5;
    private int digits_;
    /**
     * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount digits = 5;</code>
     * @return Whether the digits field is set.
     */
    @java.lang.Override public boolean hasDigits() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount digits = 5;</code>
     * @return The digits.
     */
    @java.lang.Override public cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount getDigits() {
      @SuppressWarnings("deprecation")
      cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount result = cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount.valueOf(digits_);
      return result == null ? cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount.DIGIT_COUNT_UNSPECIFIED : result;
    }

    public static final int TYPE_FIELD_NUMBER = 6;
    private int type_;
    /**
     * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType type = 6;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override public boolean hasType() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType type = 6;</code>
     * @return The type.
     */
    @java.lang.Override public cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType getType() {
      @SuppressWarnings("deprecation")
      cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType result = cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType.valueOf(type_);
      return result == null ? cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType.OTP_TYPE_UNSPECIFIED : result;
    }

    public static final int COUNTER_FIELD_NUMBER = 7;
    private long counter_;
    /**
     * <code>optional int64 counter = 7;</code>
     * @return Whether the counter field is set.
     */
    @java.lang.Override
    public boolean hasCounter() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional int64 counter = 7;</code>
     * @return The counter.
     */
    @java.lang.Override
    public long getCounter() {
      return counter_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, secret_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, issuer_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeEnum(4, algorithm_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeEnum(5, digits_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeEnum(6, type_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeInt64(7, counter_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, secret_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, issuer_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, algorithm_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, digits_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, type_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, counter_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters)) {
        return super.equals(obj);
      }
      cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters other = (cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters) obj;

      if (hasSecret() != other.hasSecret()) return false;
      if (hasSecret()) {
        if (!getSecret()
            .equals(other.getSecret())) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasIssuer() != other.hasIssuer()) return false;
      if (hasIssuer()) {
        if (!getIssuer()
            .equals(other.getIssuer())) return false;
      }
      if (hasAlgorithm() != other.hasAlgorithm()) return false;
      if (hasAlgorithm()) {
        if (algorithm_ != other.algorithm_) return false;
      }
      if (hasDigits() != other.hasDigits()) return false;
      if (hasDigits()) {
        if (digits_ != other.digits_) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (type_ != other.type_) return false;
      }
      if (hasCounter() != other.hasCounter()) return false;
      if (hasCounter()) {
        if (getCounter()
            != other.getCounter()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSecret()) {
        hash = (37 * hash) + SECRET_FIELD_NUMBER;
        hash = (53 * hash) + getSecret().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasIssuer()) {
        hash = (37 * hash) + ISSUER_FIELD_NUMBER;
        hash = (53 * hash) + getIssuer().hashCode();
      }
      if (hasAlgorithm()) {
        hash = (37 * hash) + ALGORITHM_FIELD_NUMBER;
        hash = (53 * hash) + algorithm_;
      }
      if (hasDigits()) {
        hash = (37 * hash) + DIGITS_FIELD_NUMBER;
        hash = (53 * hash) + digits_;
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasCounter()) {
        hash = (37 * hash) + COUNTER_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCounter());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters)
        cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParametersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cc.ddrpa.security.totp.migrate.google.proto.OTPAuthMigrationPayload.internal_static_cc_ddrpa_security_totp_migrate_google_proto_Payload_OtpParameters_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cc.ddrpa.security.totp.migrate.google.proto.OTPAuthMigrationPayload.internal_static_cc_ddrpa_security_totp_migrate_google_proto_Payload_OtpParameters_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters.class, cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters.Builder.class);
      }

      // Construct using cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        secret_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        issuer_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        algorithm_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        digits_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        counter_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cc.ddrpa.security.totp.migrate.google.proto.OTPAuthMigrationPayload.internal_static_cc_ddrpa_security_totp_migrate_google_proto_Payload_OtpParameters_descriptor;
      }

      @java.lang.Override
      public cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters getDefaultInstanceForType() {
        return cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters.getDefaultInstance();
      }

      @java.lang.Override
      public cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters build() {
        cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters buildPartial() {
        cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters result = new cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.secret_ = secret_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.issuer_ = issuer_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.algorithm_ = algorithm_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.digits_ = digits_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.counter_ = counter_;
          to_bitField0_ |= 0x00000040;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters) {
          return mergeFrom((cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters other) {
        if (other == cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters.getDefaultInstance()) return this;
        if (other.hasSecret()) {
          setSecret(other.getSecret());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasIssuer()) {
          bitField0_ |= 0x00000004;
          issuer_ = other.issuer_;
          onChanged();
        }
        if (other.hasAlgorithm()) {
          setAlgorithm(other.getAlgorithm());
        }
        if (other.hasDigits()) {
          setDigits(other.getDigits());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasCounter()) {
          setCounter(other.getCounter());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                secret_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                name_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                issuer_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                int tmpRaw = input.readEnum();
                cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm tmpValue =
                    cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(4, tmpRaw);
                } else {
                  algorithm_ = tmpRaw;
                  bitField0_ |= 0x00000008;
                }
                break;
              } // case 32
              case 40: {
                int tmpRaw = input.readEnum();
                cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount tmpValue =
                    cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(5, tmpRaw);
                } else {
                  digits_ = tmpRaw;
                  bitField0_ |= 0x00000010;
                }
                break;
              } // case 40
              case 48: {
                int tmpRaw = input.readEnum();
                cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType tmpValue =
                    cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(6, tmpRaw);
                } else {
                  type_ = tmpRaw;
                  bitField0_ |= 0x00000020;
                }
                break;
              } // case 48
              case 56: {
                counter_ = input.readInt64();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString secret_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes secret = 1;</code>
       * @return Whether the secret field is set.
       */
      @java.lang.Override
      public boolean hasSecret() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bytes secret = 1;</code>
       * @return The secret.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSecret() {
        return secret_;
      }
      /**
       * <code>optional bytes secret = 1;</code>
       * @param value The secret to set.
       * @return This builder for chaining.
       */
      public Builder setSecret(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        secret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes secret = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecret() {
        bitField0_ = (bitField0_ & ~0x00000001);
        secret_ = getDefaultInstance().getSecret();
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object issuer_ = "";
      /**
       * <code>optional string issuer = 3;</code>
       * @return Whether the issuer field is set.
       */
      public boolean hasIssuer() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string issuer = 3;</code>
       * @return The issuer.
       */
      public java.lang.String getIssuer() {
        java.lang.Object ref = issuer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            issuer_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string issuer = 3;</code>
       * @return The bytes for issuer.
       */
      public com.google.protobuf.ByteString
          getIssuerBytes() {
        java.lang.Object ref = issuer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          issuer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string issuer = 3;</code>
       * @param value The issuer to set.
       * @return This builder for chaining.
       */
      public Builder setIssuer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        issuer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string issuer = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIssuer() {
        bitField0_ = (bitField0_ & ~0x00000004);
        issuer_ = getDefaultInstance().getIssuer();
        onChanged();
        return this;
      }
      /**
       * <code>optional string issuer = 3;</code>
       * @param value The bytes for issuer to set.
       * @return This builder for chaining.
       */
      public Builder setIssuerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        issuer_ = value;
        onChanged();
        return this;
      }

      private int algorithm_ = 0;
      /**
       * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm algorithm = 4;</code>
       * @return Whether the algorithm field is set.
       */
      @java.lang.Override public boolean hasAlgorithm() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm algorithm = 4;</code>
       * @return The algorithm.
       */
      @java.lang.Override
      public cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm getAlgorithm() {
        @SuppressWarnings("deprecation")
        cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm result = cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm.valueOf(algorithm_);
        return result == null ? cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm.ALGORITHM_UNSPECIFIED : result;
      }
      /**
       * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm algorithm = 4;</code>
       * @param value The algorithm to set.
       * @return This builder for chaining.
       */
      public Builder setAlgorithm(cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        algorithm_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.Algorithm algorithm = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlgorithm() {
        bitField0_ = (bitField0_ & ~0x00000008);
        algorithm_ = 0;
        onChanged();
        return this;
      }

      private int digits_ = 0;
      /**
       * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount digits = 5;</code>
       * @return Whether the digits field is set.
       */
      @java.lang.Override public boolean hasDigits() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount digits = 5;</code>
       * @return The digits.
       */
      @java.lang.Override
      public cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount getDigits() {
        @SuppressWarnings("deprecation")
        cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount result = cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount.valueOf(digits_);
        return result == null ? cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount.DIGIT_COUNT_UNSPECIFIED : result;
      }
      /**
       * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount digits = 5;</code>
       * @param value The digits to set.
       * @return This builder for chaining.
       */
      public Builder setDigits(cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        digits_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.DigitCount digits = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDigits() {
        bitField0_ = (bitField0_ & ~0x00000010);
        digits_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType type = 6;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override public boolean hasType() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType type = 6;</code>
       * @return The type.
       */
      @java.lang.Override
      public cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType getType() {
        @SuppressWarnings("deprecation")
        cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType result = cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType.valueOf(type_);
        return result == null ? cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType.OTP_TYPE_UNSPECIFIED : result;
      }
      /**
       * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType type = 6;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpType type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = 0;
        onChanged();
        return this;
      }

      private long counter_ ;
      /**
       * <code>optional int64 counter = 7;</code>
       * @return Whether the counter field is set.
       */
      @java.lang.Override
      public boolean hasCounter() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional int64 counter = 7;</code>
       * @return The counter.
       */
      @java.lang.Override
      public long getCounter() {
        return counter_;
      }
      /**
       * <code>optional int64 counter = 7;</code>
       * @param value The counter to set.
       * @return This builder for chaining.
       */
      public Builder setCounter(long value) {
        bitField0_ |= 0x00000040;
        counter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 counter = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCounter() {
        bitField0_ = (bitField0_ & ~0x00000040);
        counter_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters)
    }

    // @@protoc_insertion_point(class_scope:cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters)
    private static final cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters();
    }

    public static cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<OtpParameters>
        PARSER = new com.google.protobuf.AbstractParser<OtpParameters>() {
      @java.lang.Override
      public OtpParameters parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OtpParameters> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OtpParameters> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int OTP_PARAMETERS_FIELD_NUMBER = 1;
  private java.util.List<cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters> otpParameters_;
  /**
   * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
   */
  @java.lang.Override
  public java.util.List<cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters> getOtpParametersList() {
    return otpParameters_;
  }
  /**
   * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParametersOrBuilder> 
      getOtpParametersOrBuilderList() {
    return otpParameters_;
  }
  /**
   * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
   */
  @java.lang.Override
  public int getOtpParametersCount() {
    return otpParameters_.size();
  }
  /**
   * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
   */
  @java.lang.Override
  public cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters getOtpParameters(int index) {
    return otpParameters_.get(index);
  }
  /**
   * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
   */
  @java.lang.Override
  public cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParametersOrBuilder getOtpParametersOrBuilder(
      int index) {
    return otpParameters_.get(index);
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  private int version_;
  /**
   * <code>optional int32 version = 2;</code>
   * @return Whether the version field is set.
   */
  @java.lang.Override
  public boolean hasVersion() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 version = 2;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int BATCH_SIZE_FIELD_NUMBER = 3;
  private int batchSize_;
  /**
   * <code>optional int32 batch_size = 3;</code>
   * @return Whether the batchSize field is set.
   */
  @java.lang.Override
  public boolean hasBatchSize() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int32 batch_size = 3;</code>
   * @return The batchSize.
   */
  @java.lang.Override
  public int getBatchSize() {
    return batchSize_;
  }

  public static final int BATCH_INDEX_FIELD_NUMBER = 4;
  private int batchIndex_;
  /**
   * <code>optional int32 batch_index = 4;</code>
   * @return Whether the batchIndex field is set.
   */
  @java.lang.Override
  public boolean hasBatchIndex() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 batch_index = 4;</code>
   * @return The batchIndex.
   */
  @java.lang.Override
  public int getBatchIndex() {
    return batchIndex_;
  }

  public static final int BATCH_ID_FIELD_NUMBER = 5;
  private int batchId_;
  /**
   * <code>optional int32 batch_id = 5;</code>
   * @return Whether the batchId field is set.
   */
  @java.lang.Override
  public boolean hasBatchId() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional int32 batch_id = 5;</code>
   * @return The batchId.
   */
  @java.lang.Override
  public int getBatchId() {
    return batchId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < otpParameters_.size(); i++) {
      output.writeMessage(1, otpParameters_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(2, version_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(3, batchSize_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(4, batchIndex_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt32(5, batchId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < otpParameters_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, otpParameters_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, version_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, batchSize_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, batchIndex_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, batchId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cc.ddrpa.security.totp.migrate.google.proto.Payload)) {
      return super.equals(obj);
    }
    cc.ddrpa.security.totp.migrate.google.proto.Payload other = (cc.ddrpa.security.totp.migrate.google.proto.Payload) obj;

    if (!getOtpParametersList()
        .equals(other.getOtpParametersList())) return false;
    if (hasVersion() != other.hasVersion()) return false;
    if (hasVersion()) {
      if (getVersion()
          != other.getVersion()) return false;
    }
    if (hasBatchSize() != other.hasBatchSize()) return false;
    if (hasBatchSize()) {
      if (getBatchSize()
          != other.getBatchSize()) return false;
    }
    if (hasBatchIndex() != other.hasBatchIndex()) return false;
    if (hasBatchIndex()) {
      if (getBatchIndex()
          != other.getBatchIndex()) return false;
    }
    if (hasBatchId() != other.hasBatchId()) return false;
    if (hasBatchId()) {
      if (getBatchId()
          != other.getBatchId()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getOtpParametersCount() > 0) {
      hash = (37 * hash) + OTP_PARAMETERS_FIELD_NUMBER;
      hash = (53 * hash) + getOtpParametersList().hashCode();
    }
    if (hasVersion()) {
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
    }
    if (hasBatchSize()) {
      hash = (37 * hash) + BATCH_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getBatchSize();
    }
    if (hasBatchIndex()) {
      hash = (37 * hash) + BATCH_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getBatchIndex();
    }
    if (hasBatchId()) {
      hash = (37 * hash) + BATCH_ID_FIELD_NUMBER;
      hash = (53 * hash) + getBatchId();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cc.ddrpa.security.totp.migrate.google.proto.Payload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cc.ddrpa.security.totp.migrate.google.proto.Payload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cc.ddrpa.security.totp.migrate.google.proto.Payload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cc.ddrpa.security.totp.migrate.google.proto.Payload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cc.ddrpa.security.totp.migrate.google.proto.Payload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cc.ddrpa.security.totp.migrate.google.proto.Payload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cc.ddrpa.security.totp.migrate.google.proto.Payload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cc.ddrpa.security.totp.migrate.google.proto.Payload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cc.ddrpa.security.totp.migrate.google.proto.Payload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cc.ddrpa.security.totp.migrate.google.proto.Payload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cc.ddrpa.security.totp.migrate.google.proto.Payload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cc.ddrpa.security.totp.migrate.google.proto.Payload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cc.ddrpa.security.totp.migrate.google.proto.Payload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cc.ddrpa.security.totp.migrate.google.proto.Payload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cc.ddrpa.security.totp.migrate.google.proto.Payload)
      cc.ddrpa.security.totp.migrate.google.proto.PayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cc.ddrpa.security.totp.migrate.google.proto.OTPAuthMigrationPayload.internal_static_cc_ddrpa_security_totp_migrate_google_proto_Payload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cc.ddrpa.security.totp.migrate.google.proto.OTPAuthMigrationPayload.internal_static_cc_ddrpa_security_totp_migrate_google_proto_Payload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cc.ddrpa.security.totp.migrate.google.proto.Payload.class, cc.ddrpa.security.totp.migrate.google.proto.Payload.Builder.class);
    }

    // Construct using cc.ddrpa.security.totp.migrate.google.proto.Payload.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (otpParametersBuilder_ == null) {
        otpParameters_ = java.util.Collections.emptyList();
      } else {
        otpParameters_ = null;
        otpParametersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      batchSize_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      batchIndex_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      batchId_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cc.ddrpa.security.totp.migrate.google.proto.OTPAuthMigrationPayload.internal_static_cc_ddrpa_security_totp_migrate_google_proto_Payload_descriptor;
    }

    @java.lang.Override
    public cc.ddrpa.security.totp.migrate.google.proto.Payload getDefaultInstanceForType() {
      return cc.ddrpa.security.totp.migrate.google.proto.Payload.getDefaultInstance();
    }

    @java.lang.Override
    public cc.ddrpa.security.totp.migrate.google.proto.Payload build() {
      cc.ddrpa.security.totp.migrate.google.proto.Payload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cc.ddrpa.security.totp.migrate.google.proto.Payload buildPartial() {
      cc.ddrpa.security.totp.migrate.google.proto.Payload result = new cc.ddrpa.security.totp.migrate.google.proto.Payload(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (otpParametersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          otpParameters_ = java.util.Collections.unmodifiableList(otpParameters_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.otpParameters_ = otpParameters_;
      } else {
        result.otpParameters_ = otpParametersBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.version_ = version_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.batchSize_ = batchSize_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.batchIndex_ = batchIndex_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.batchId_ = batchId_;
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cc.ddrpa.security.totp.migrate.google.proto.Payload) {
        return mergeFrom((cc.ddrpa.security.totp.migrate.google.proto.Payload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cc.ddrpa.security.totp.migrate.google.proto.Payload other) {
      if (other == cc.ddrpa.security.totp.migrate.google.proto.Payload.getDefaultInstance()) return this;
      if (otpParametersBuilder_ == null) {
        if (!other.otpParameters_.isEmpty()) {
          if (otpParameters_.isEmpty()) {
            otpParameters_ = other.otpParameters_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOtpParametersIsMutable();
            otpParameters_.addAll(other.otpParameters_);
          }
          onChanged();
        }
      } else {
        if (!other.otpParameters_.isEmpty()) {
          if (otpParametersBuilder_.isEmpty()) {
            otpParametersBuilder_.dispose();
            otpParametersBuilder_ = null;
            otpParameters_ = other.otpParameters_;
            bitField0_ = (bitField0_ & ~0x00000001);
            otpParametersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOtpParametersFieldBuilder() : null;
          } else {
            otpParametersBuilder_.addAllMessages(other.otpParameters_);
          }
        }
      }
      if (other.hasVersion()) {
        setVersion(other.getVersion());
      }
      if (other.hasBatchSize()) {
        setBatchSize(other.getBatchSize());
      }
      if (other.hasBatchIndex()) {
        setBatchIndex(other.getBatchIndex());
      }
      if (other.hasBatchId()) {
        setBatchId(other.getBatchId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters m =
                  input.readMessage(
                      cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters.PARSER,
                      extensionRegistry);
              if (otpParametersBuilder_ == null) {
                ensureOtpParametersIsMutable();
                otpParameters_.add(m);
              } else {
                otpParametersBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              version_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              batchSize_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              batchIndex_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              batchId_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters> otpParameters_ =
      java.util.Collections.emptyList();
    private void ensureOtpParametersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        otpParameters_ = new java.util.ArrayList<cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters>(otpParameters_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters, cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters.Builder, cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParametersOrBuilder> otpParametersBuilder_;

    /**
     * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
     */
    public java.util.List<cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters> getOtpParametersList() {
      if (otpParametersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(otpParameters_);
      } else {
        return otpParametersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
     */
    public int getOtpParametersCount() {
      if (otpParametersBuilder_ == null) {
        return otpParameters_.size();
      } else {
        return otpParametersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
     */
    public cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters getOtpParameters(int index) {
      if (otpParametersBuilder_ == null) {
        return otpParameters_.get(index);
      } else {
        return otpParametersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
     */
    public Builder setOtpParameters(
        int index, cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters value) {
      if (otpParametersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOtpParametersIsMutable();
        otpParameters_.set(index, value);
        onChanged();
      } else {
        otpParametersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
     */
    public Builder setOtpParameters(
        int index, cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters.Builder builderForValue) {
      if (otpParametersBuilder_ == null) {
        ensureOtpParametersIsMutable();
        otpParameters_.set(index, builderForValue.build());
        onChanged();
      } else {
        otpParametersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
     */
    public Builder addOtpParameters(cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters value) {
      if (otpParametersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOtpParametersIsMutable();
        otpParameters_.add(value);
        onChanged();
      } else {
        otpParametersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
     */
    public Builder addOtpParameters(
        int index, cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters value) {
      if (otpParametersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOtpParametersIsMutable();
        otpParameters_.add(index, value);
        onChanged();
      } else {
        otpParametersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
     */
    public Builder addOtpParameters(
        cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters.Builder builderForValue) {
      if (otpParametersBuilder_ == null) {
        ensureOtpParametersIsMutable();
        otpParameters_.add(builderForValue.build());
        onChanged();
      } else {
        otpParametersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
     */
    public Builder addOtpParameters(
        int index, cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters.Builder builderForValue) {
      if (otpParametersBuilder_ == null) {
        ensureOtpParametersIsMutable();
        otpParameters_.add(index, builderForValue.build());
        onChanged();
      } else {
        otpParametersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
     */
    public Builder addAllOtpParameters(
        java.lang.Iterable<? extends cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters> values) {
      if (otpParametersBuilder_ == null) {
        ensureOtpParametersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, otpParameters_);
        onChanged();
      } else {
        otpParametersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
     */
    public Builder clearOtpParameters() {
      if (otpParametersBuilder_ == null) {
        otpParameters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        otpParametersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
     */
    public Builder removeOtpParameters(int index) {
      if (otpParametersBuilder_ == null) {
        ensureOtpParametersIsMutable();
        otpParameters_.remove(index);
        onChanged();
      } else {
        otpParametersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
     */
    public cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters.Builder getOtpParametersBuilder(
        int index) {
      return getOtpParametersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
     */
    public cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParametersOrBuilder getOtpParametersOrBuilder(
        int index) {
      if (otpParametersBuilder_ == null) {
        return otpParameters_.get(index);  } else {
        return otpParametersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
     */
    public java.util.List<? extends cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParametersOrBuilder> 
         getOtpParametersOrBuilderList() {
      if (otpParametersBuilder_ != null) {
        return otpParametersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(otpParameters_);
      }
    }
    /**
     * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
     */
    public cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters.Builder addOtpParametersBuilder() {
      return getOtpParametersFieldBuilder().addBuilder(
          cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters.getDefaultInstance());
    }
    /**
     * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
     */
    public cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters.Builder addOtpParametersBuilder(
        int index) {
      return getOtpParametersFieldBuilder().addBuilder(
          index, cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters.getDefaultInstance());
    }
    /**
     * <code>repeated .cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters otp_parameters = 1;</code>
     */
    public java.util.List<cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters.Builder> 
         getOtpParametersBuilderList() {
      return getOtpParametersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters, cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters.Builder, cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParametersOrBuilder> 
        getOtpParametersFieldBuilder() {
      if (otpParametersBuilder_ == null) {
        otpParametersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters, cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParameters.Builder, cc.ddrpa.security.totp.migrate.google.proto.Payload.OtpParametersOrBuilder>(
                otpParameters_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        otpParameters_ = null;
      }
      return otpParametersBuilder_;
    }

    private int version_ ;
    /**
     * <code>optional int32 version = 2;</code>
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>optional int32 version = 2;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      bitField0_ |= 0x00000002;
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000002);
      version_ = 0;
      onChanged();
      return this;
    }

    private int batchSize_ ;
    /**
     * <code>optional int32 batch_size = 3;</code>
     * @return Whether the batchSize field is set.
     */
    @java.lang.Override
    public boolean hasBatchSize() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 batch_size = 3;</code>
     * @return The batchSize.
     */
    @java.lang.Override
    public int getBatchSize() {
      return batchSize_;
    }
    /**
     * <code>optional int32 batch_size = 3;</code>
     * @param value The batchSize to set.
     * @return This builder for chaining.
     */
    public Builder setBatchSize(int value) {
      bitField0_ |= 0x00000004;
      batchSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 batch_size = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBatchSize() {
      bitField0_ = (bitField0_ & ~0x00000004);
      batchSize_ = 0;
      onChanged();
      return this;
    }

    private int batchIndex_ ;
    /**
     * <code>optional int32 batch_index = 4;</code>
     * @return Whether the batchIndex field is set.
     */
    @java.lang.Override
    public boolean hasBatchIndex() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 batch_index = 4;</code>
     * @return The batchIndex.
     */
    @java.lang.Override
    public int getBatchIndex() {
      return batchIndex_;
    }
    /**
     * <code>optional int32 batch_index = 4;</code>
     * @param value The batchIndex to set.
     * @return This builder for chaining.
     */
    public Builder setBatchIndex(int value) {
      bitField0_ |= 0x00000008;
      batchIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 batch_index = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBatchIndex() {
      bitField0_ = (bitField0_ & ~0x00000008);
      batchIndex_ = 0;
      onChanged();
      return this;
    }

    private int batchId_ ;
    /**
     * <code>optional int32 batch_id = 5;</code>
     * @return Whether the batchId field is set.
     */
    @java.lang.Override
    public boolean hasBatchId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 batch_id = 5;</code>
     * @return The batchId.
     */
    @java.lang.Override
    public int getBatchId() {
      return batchId_;
    }
    /**
     * <code>optional int32 batch_id = 5;</code>
     * @param value The batchId to set.
     * @return This builder for chaining.
     */
    public Builder setBatchId(int value) {
      bitField0_ |= 0x00000010;
      batchId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 batch_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBatchId() {
      bitField0_ = (bitField0_ & ~0x00000010);
      batchId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cc.ddrpa.security.totp.migrate.google.proto.Payload)
  }

  // @@protoc_insertion_point(class_scope:cc.ddrpa.security.totp.migrate.google.proto.Payload)
  private static final cc.ddrpa.security.totp.migrate.google.proto.Payload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cc.ddrpa.security.totp.migrate.google.proto.Payload();
  }

  public static cc.ddrpa.security.totp.migrate.google.proto.Payload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Payload>
      PARSER = new com.google.protobuf.AbstractParser<Payload>() {
    @java.lang.Override
    public Payload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Payload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Payload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cc.ddrpa.security.totp.migrate.google.proto.Payload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

